- block: # Only configure when os is Debian

  - name: Delete files that must be absent.
    file:
      path: "{{ item.dest }}"
      state: absent
    with_items: "{{ debian_unstable_files }}"
    when: item.state | default('present') == 'absent'

  - name: Configure additional repositories.
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: 0644
    when: item.state | default('present') == 'present'
    with_items: "{{ debian_unstable_files }}"
    register: _unstable_config_result

  - name: Update apt cache.
    apt:
      update_cache: yes
    when: _unstable_config_result.changed

  when:
    - ansible_distribution == 'Debian'
